interface ZIF_I_TICKET_BO_V2_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_TICKET_BO_V2,
 CREATE_ZI_TICKET_BO_V2         TYPE /BOBF/ACT_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FEEAF7',
 DELETE_ZI_TICKET_BO_V2         TYPE /BOBF/ACT_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FF6AF7',
 LOCK_ZI_TICKET_BO_V2           TYPE /BOBF/ACT_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FE2AF7',
 SAVE_ZI_TICKET_BO_V2           TYPE /BOBF/ACT_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FFEAF7',
 UNLOCK_ZI_TICKET_BO_V2         TYPE /BOBF/ACT_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FE6AF7',
 UPDATE_ZI_TICKET_BO_V2         TYPE /BOBF/ACT_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FF2AF7',
 VALIDATE_ZI_TICKET_BO_V2       TYPE /BOBF/ACT_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FFAAF7',
      END OF ZI_TICKET_BO_V2,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_TICKET_BO_V2,
        BEGIN OF LOCK_ZI_TICKET_BO_V2,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_TICKET_BO_V2,
        BEGIN OF UNLOCK_ZI_TICKET_BO_V2,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_TICKET_BO_V2,
      END OF ZI_TICKET_BO_V2,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_TICKET_BO_V2,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '7FCCAD0192B01EEDAAAD392D7A6A8AF7',
      END OF ZI_TICKET_BO_V2,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_TICKET_BO_V2,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FE0AF7',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FDCAF7',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FECAF7',
      END OF ZI_TICKET_BO_V2,
      BEGIN OF ZI_TICKET_BO_V2_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '7FCCAD0192B01EEDAAAD38C676004AF7',
      END OF ZI_TICKET_BO_V2_LOCK,
      BEGIN OF ZI_TICKET_BO_V2_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '7FCCAD0192B01EEDAAAD38C676002AF7',
      END OF ZI_TICKET_BO_V2_MESSAGE,
      BEGIN OF ZI_TICKET_BO_V2_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '7FCCAD0192B01EEDAAAD38C676006AF7',
      END OF ZI_TICKET_BO_V2_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_TICKET_BO_V2,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_TICKET_BO_V2,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '7FCCAD0192B01EEDAAAD38A6C76A6AF7' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_TICKET_BO_V2' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_TICKET_BO_V2,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '7FCCAD0192B01EEDAAAD392D7A6AAAF7',
      END OF ZI_TICKET_BO_V2,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_TICKET_BO_V2                TYPE /BOBF/OBM_GROUP_KEY VALUE '7FCCAD0192B01EEDAAAD392D7A70AAF7',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_TICKET_BO_V2                TYPE /BOBF/OBM_NODE_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FD6AF7',
 ZI_TICKET_BO_V2_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FDEAF7',
 ZI_TICKET_BO_V2_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FDAAF7',
 ZI_TICKET_BO_V2_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FEAAF7',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_TICKET_BO_V2,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CARRID                         TYPE STRING VALUE 'CARRID',
  CONNID                         TYPE STRING VALUE 'CONNID',
  FLDATE                         TYPE STRING VALUE 'FLDATE',
  BOOKID                         TYPE STRING VALUE 'BOOKID',
  CUSTOMID                       TYPE STRING VALUE 'CUSTOMID',
  TICKET                         TYPE STRING VALUE 'TICKET',
  PLACE                          TYPE STRING VALUE 'PLACE',
  ARCHIVE_                       TYPE STRING VALUE 'ARCHIVE_',
      END OF ZI_TICKET_BO_V2,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_TICKET_BO_V2,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '7FCCAD0192B01EEDAAAD38C675FD8AF7',
      END OF ZI_TICKET_BO_V2,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_TICKET_BO_V2,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '7FCCAD0192B01EEDAAAD392D7A6B8AF7',
      END OF ZI_TICKET_BO_V2,
    END OF SC_VALIDATION .
endinterface.
